packages:
  - apps/*
  - packages/*

catalog:
  '@babel/core': ^7.20.0
  '@commitlint/cli': ^20.2.0
  '@commitlint/config-conventional': ^20.2.0
  '@hookform/resolvers': ^3.3.4
  '@keyv/redis': ^4.1.2
  '@nestjs/axios': ^4.0.1
  '@nestjs/bullmq': ^11.0.4
  '@nestjs/cache-manager': ^3.1.0
  '@nestjs/cli': ^11.0.14
  '@nestjs/common': ^11.1.10
  '@nestjs/config': ^4.0.2
  '@nestjs/core': ^11.1.10
  '@nestjs/jwt': ^11.0.2
  '@nestjs/passport': ^11.0.5
  '@nestjs/platform-express': ^11.1.10
  '@nestjs/platform-socket.io': ^11.1.10
  '@nestjs/schedule': ^6.1.0
  '@nestjs/schematics': ^11.0.9
  '@nestjs/swagger': ^11.2.3
  '@nestjs/terminus': ^11.0.0
  '@nestjs/testing': ^11.1.10
  '@nestjs/throttler': ^6.5.0
  '@nestjs/websockets': ^11.1.10
  '@next/bundle-analyzer': ^15.1.6
  '@opentelemetry/api': ^1.9.0
  '@opentelemetry/auto-instrumentations-node': ^0.52.1
  '@opentelemetry/exporter-trace-otlp-http': ^0.54.2
  '@opentelemetry/instrumentation': ^0.208.0
  '@opentelemetry/instrumentation-express': ^0.57.1
  '@opentelemetry/instrumentation-http': ^0.208.0
  '@opentelemetry/resources': ^1.28.0
  '@opentelemetry/sdk-node': ^0.54.2
  '@opentelemetry/sdk-trace-base': ^1.28.0
  '@opentelemetry/sdk-trace-node': ^2.2.0
  '@opentelemetry/semantic-conventions': ^1.28.0
  '@playwright/test': ^1.57.0
  '@prisma/adapter-pg': 7.2.0
  '@prisma/client': 7.2.0
  '@radix-ui/react-accordion': ^1.2.12
  '@react-native-async-storage/async-storage': ^2.2.0
  '@react-native-community/netinfo': ^11.4.1
  '@react-native-ml-kit/text-recognition': ^2.0.0
  '@react-navigation/bottom-tabs': ^7.9.0
  '@react-navigation/native': ^7.1.26
  '@react-navigation/stack': ^7.6.13
  '@sentry/nestjs': ^10.32.1
  '@sentry/node': ^10.32.1
  '@sentry/profiling-node': ^1.3.5
  '@tanstack/react-query': ^5.90.12
  '@testing-library/jest-dom': ^6.9.1
  '@testing-library/react': ^16.3.1
  '@testing-library/user-event': ^14.6.1
  '@types/bcryptjs': ^3.0.0
  '@types/cookie-parser': ^1.4.10
  '@types/express': ^4.17.17
  '@types/jest': 30.0.0
  '@types/multer': ^1.4.11
  '@types/node': ^25.0.3
  '@types/nodemailer': ^7.0.4
  '@types/passport-jwt': ^4.0.1
  '@types/pg': ^8.11.10
  '@types/qrcode': ^1.5.5
  '@types/qrcode-terminal': ^0.12.2
  '@types/react': ^18.2.57
  '@types/react-dom': ^18.2.19
  '@types/speakeasy': ^2.0.10
  '@types/supertest': ^6.0.0
  '@typescript-eslint/eslint-plugin': ^8.51.0
  '@typescript-eslint/parser': ^8.51.0
  '@whiskeysockets/baileys': ^6.7.9
  autoprefixer: ^10.4.17
  axios: ^1.6.7
  axios-mock-adapter: ^1.22.0
  bcryptjs: ^3.0.3
  bullmq: ^5.65.1
  cache-manager: ^7.2.7
  class-transformer: ^0.5.1
  class-validator: ^0.14.1
  clsx: ^2.1.0
  cookie-parser: ^1.4.7
  date-fns: ^3.6.0
  dotenv: ^16.4.5
  dotenv-cli: ^11.0.0
  eslint: ^9.39.2
  eslint-config-next: ^16.0.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-prettier: ^5.5.4
  expo: ~54.0.30
  expo-camera: ^17.0.10
  expo-constants: ~17.0.0
  expo-device: ~7.0.0
  expo-image-picker: ^17.0.10
  expo-local-authentication: ~17.0.0
  expo-location: ^19.0.8
  expo-media-library: ^18.2.1
  expo-notifications: ~0.29.0
  expo-secure-store: ~15.0.0
  expo-sqlite: ^16.0.10
  expo-status-bar: ~3.0.9
  express: ^4.18.2
  form-data: ^4.0.0
  fs-extra: ^11.3.3
  husky: ^9.1.7
  identity-obj-proxy: ^3.0.0
  ioredis: ^5.3.2
  jest: 30.2.0
  jest-environment-jsdom: ^30.2.0
  js-yaml: ^4.1.0
  keyv: ^5.2.2
  lint-staged: ^16.2.7
  lucide-react: ^0.344.0
  nestjs-zod: ^3.0.0
  next: ^16.0.0
  nodemailer: ^7.0.11
  passport: ^0.7.0
  passport-jwt: ^4.0.1
  pg: ^8.13.1
  pino: ^9.0.0
  postcss: ^8.4.35
  prettier: ^3.7.4
  prisma: 7.2.0
  prom-client: ^15.1.3
  qrcode: ^1.5.4
  qrcode-terminal: ^0.12.0
  react: ^18.2.0
  react-dom: ^18.2.0
  react-hook-form: ^7.51.0
  react-native: 0.81.5
  react-native-chart-kit: ^6.12.0
  react-native-gesture-handler: ^2.28.0
  react-native-maps: ^1.26.20
  react-native-paper: ^5.14.5
  react-native-safe-area-context: ^5.6.2
  react-native-screens: ^4.16.0
  react-native-svg: ^15.15.1
  react-native-uuid: ^2.0.3
  react-native-vector-icons: ^10.3.0
  react-native-vision-camera: ^4.7.3
  react-native-web: ~0.19.13
  recharts: ^2.12.2
  redis: ^4.6.13
  reflect-metadata: ^0.1.13
  rimraf: ^6.1.2
  rxjs: ^7.8.1
  socket.io: ^4.8.1
  source-map-support: ^0.5.21
  speakeasy: ^2.0.0
  stripe: ^14.14.0
  supertest: ^6.3.3
  tailwind-merge: ^2.2.1
  tailwindcss: ^3.4.1
  telegraf: ^4.15.3
  telegraf-session-local: ^2.1.1
  tesseract.js: ^5.0.4
  ts-jest: 29.4.6
  ts-loader: ^9.4.3
  ts-node: ^10.9.1
  tsconfig-paths: ^4.2.0
  tsx: ^4.19.0
  turbo: ^2.7.2
  typescript: ^5.9.3
  winston: ^3.19.0
  yahoo-finance2: ^3.10.2
  zod: ^3.22.4
