export const CATEGORY_KEYWORDS: Record<string, string[]> = {
  Alimentação: [
    'ifood',
    'uber eats',
    'restaurante',
    'padaria',
    'supermercado',
    'mc donalds',
    'burger king',
    'starbucks',
    'fome',
  ],
  Transporte: [
    'uber',
    '99',
    'taxi',
    'posto',
    'combustivel',
    'gasolina',
    'ipiranga',
    'shell',
    'estacionamento',
    'metro',
  ],
  Lazer: [
    'netflix',
    'spotify',
    'amazon prime',
    'cinema',
    'steam',
    'playstation',
    'xbox',
    'bar',
    'show',
  ],
  Saúde: ['farmacia', 'drogasil', 'medico', 'hospital', 'dentista', 'exame', 'psicologo'],
  Educação: ['udemy', 'alura', 'curso', 'livraria', 'faculdade', 'escola', 'leitura'],
  Moradia: [
    'aluguel',
    'condominio',
    'luz',
    'agua',
    'internet',
    'vivo',
    'claro',
    'tim',
    'oi',
    'gas',
  ],
  Salário: ['pagamento', 'salario', 'ted recebida', 'pix recebido', 'proventos'],
  Investimentos: ['corretora', 'b3', 'tesouro', 'cdb', 'bitcoin', 'cripto', 'binance'],
};
