export declare enum ConsentType {
  TERMS_OF_SERVICE = 'TERMS_OF_SERVICE',
  PRIVACY_POLICY = 'PRIVACY_POLICY',
  MARKETING = 'MARKETING',
  ANALYTICS = 'ANALYTICS',
  COOKIES = 'COOKIES',
  DATA_SHARING = 'DATA_SHARING',
  PROFILING = 'PROFILING',
  THIRD_PARTY = 'THIRD_PARTY',
}
//# sourceMappingURL=consent-type.enum.d.ts.map
